# CrazySpawner config.yml
# For more information visit
# https://github.com/ST-DDT/Crazy/blob/master/CrazySpawner/src/config.yml
version: X.Y
# required plugins +version can be found there
# https://github.com/ST-DDT/Crazy/blob/master/CrazySpawner/src/plugin.yml
# the chat header used ingame (this cannot be changed via any kind of reload)
chatHeader: '&C[&ACrazySpawner&C] &F'
# This section is only used as example and can be removed.
example:
  creature:
# The Name of your creature type
    name: String
# The Type of your creature type
# For a full list visit the javadocs page
# http://jd.bukkit.org/rb/apidocs/org/bukkit/entity/EntityType.html#enum_constant_summary
# WARNING: ONLY USE LIVING TYPES SUCH AS MONSTERS AND ANIMALS.
    type: EntityType
# Spawn as baby (Villager and Animals)
    baby: boolean
# Spawn as Zombievillager (Zombie)
    villager: boolean
# Spawn as Witherskeleton (Skeleton) 
    wither: boolean
# Spawn as ChargedCreeper (Creeper)
    charged: boolean
# Spawn as colored sheep (Colorable (Sheep))
# For a full list visit the javadocs page
# http://jd.bukkit.org/rb/apidocs/org/bukkit/DyeColor.html#enum_constant_summary
    color: DyeColor
# Spawn sized slime (Clime + Magma_Cube)
    size: int (1-4)
# Spawn as angry wolf (Wolf)
    angry: boolean
# Spawn as tamed pet (Tameable (Wolf + Ocelot/Cat))
    tamed: boolean
# Spawn as tamed pet owned by player (Tameable (Wolf + Ocelot/Cat))
    tamer: Player
# Spawn with additional health
    maxHealth: int
# Spawn with boots
    boots: Item
    bootsDropChance: float (0-1)
# Spawn with leggings
    leggings: Item
    leggingsDropChance: float (0-1)
# Spawn with chestplate
    chestplate: Item
    chestplateDropChance: float (0-1)
# Spawn with helmet
    helmet: Item
    helmetDropChance: float (0-1)
# Spawn with item in hand (ex: sword)
    itemInHand: Item
    itemInHandDropChance: float (0-1)
# Spawn with passenger
# This can be all types listed in "/cms creature:" command
# If you are using a custom type here you have to define it bevore this entry.
    passenger: ExtendedCreatureType
# Items have to be defined this way
  Item:
# Material Type
# For a full list visit the javadocs page
# http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html#enum_constant_summary
    type: Material
# damage value, the higher the more damaged
# also known as durability
    damage: short (0 (full) - 528 (broken, upper limit may differ (mostly below)))
# the item count in this stack
    amount: int (1-64)
    meta:
# If you keep the meta section, do not edit these lines (START).
      ==: ItemMeta
      meta-type: UNSPECIFIC
# If you keep the meta section, do not edit these lines (END).
# The items display name
      display-name: String
# The items description/lore
      lore:
      - Line1
      - Line2
      - '...'
# All enchantments should be listed here
# For a full list visit the javadocs page
# http://jd.bukkit.org/rb/apidocs/org/bukkit/enchantments/Enchantment.html#field_summary
      enchants:
        ENCHANTMENT1: int (1-255)
        ENCHANTMENT2: int (1-255)
        ENCHANTMENTx: int (1-255)
# All custom creatures have to be defined here
##creatures: {}
# All spawn task are defined here
##tasks: {}
